# Generated by Django 4.2.7 on 2023-11-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('required', models.BooleanField()),
                ('text', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=10)),
                ('programming_stack', models.CharField(blank=True, max_length=20)),
                ('date_responded', models.DateTimeField(auto_now_add=True)),
                ('certificates', models.ManyToManyField(to='SimpleSurveyApp.certificate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleSurveyApp.question')),
            ],
        ),
    ]
