# Generated by Django 4.2.7 on 2023-11-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleSurveyApp', '0002_rename_response_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_value', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=10)),
                ('PS_value', models.CharField(choices=[('REACT', 'React Js'), ('ANGULAR', 'Angular Js'), ('VUE', 'Vue Js'), ('SQL', 'Sql'), ('POSTGRES', 'Postgres'), ('MYSQL', 'Mysql'), ('JAVA', 'Java'), ('PHP', 'Php'), ('GO', 'Go'), ('RUST', 'Rust')], max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='SimpleSurveyApp.question')),
            ],
        ),
    ]
