# Generated by Django 4.2.7 on 2023-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleSurveyApp', '0003_alter_surveyresponse_gender_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='G_value',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='choice',
            name='PS_value',
            field=models.CharField(blank=True, choices=[('REACT', 'React Js'), ('ANGULAR', 'Angular Js'), ('VUE', 'Vue Js'), ('SQL', 'Sql'), ('POSTGRES', 'Postgres'), ('MYSQL', 'Mysql'), ('JAVA', 'Java'), ('PHP', 'Php'), ('GO', 'Go'), ('RUST', 'Rust')], max_length=50),
        ),
    ]
