# Generated by Django 4.2.7 on 2023-11-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleSurveyApp', '0004_alter_choice_g_value_alter_choice_ps_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SimpleSurveyApp.question'),
        ),
    ]
