# Generated by Django 4.2.7 on 2023-11-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleSurveyApp', '0009_alter_certificate_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='certificates',
            new_name='my_certs',
        ),
    ]
