# Generated by Django 4.2.7 on 2023-11-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleSurveyApp', '0010_rename_certificates_surveyresponse_my_certs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(upload_to=''),
        ),
    ]
