# Generated by Django 4.2.7 on 2023-11-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleSurveyApp', '0012_remove_surveyresponse_my_certs_delete_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='my_certs',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='programming_stack',
            field=models.CharField(max_length=20),
        ),
    ]
